name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, product-service, order-service, payment-service, gateway]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          if [ "${{ matrix.service }}" == "gateway" ]; then
            docker build -t ecommerce/${{ matrix.service }}:${{ github.sha }} ./gateway
          else
            docker build -t ecommerce/${{ matrix.service }}:${{ github.sha }} ./services/${{ matrix.service }}
          fi
